language: android
dist: trusty
android:
  components:
    - android-28
    - build-tools-28.0.3

env:
  global:
    # install timeout in minutes (2 minutes by default)
    - ADB_INSTALL_TIMEOUT=8

# stages
jobs:
  include:
    - stage: compile
      script: ./gradlew clean :googlepay:assembleDebug :googlepay:assembleRelease
    - stage: publish
      if: branch = master
      script: ./gradlew :googlepay:bintrayUpload
